services:
  dataflow-db:
    image: postgres:13
    container_name: weatherwise-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherwise-db
    ports:
      - "5432:5432"
    volumes:
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data-system-network

networks:
  data-system-network:
    driver: bridge